Refactor/server
Wyna-7/digestwell-repo pull request #14
Opened 2024-06-14 12:03 UTC by sebastiandve

Refactored:

- models
- controllers
- env variables

2024-06-14 12:09 UTC, Wyna-7 commented on server/index.js
> +var corsOptions = {
should this be const?

2024-06-14 12:09 UTC, sebastiandve commented on server/index.js
> +var corsOptions = {
yes nice catch

2024-06-14 12:14 UTC, Wyna-7 commented on server/controllers/util.js
> +    res.status(500).send();
Instead of consolo logging the errors:
res.status(500).send(`There has been an error: ${err.message}`); ??

2024-06-14 12:17 UTC, Wyna-7 commented on server/controllers/index.js
No comment, just mind blown that you can do this 🤯

2024-06-14 12:19 UTC, tatyanabortnik commented on server/controllers/index.js
I feel the same

2024-06-14 12:22 UTC, tatyanabortnik requested changes
2 comments from Queralt that need attention

2024-06-14 13:00 UTC, sebastiandve commented on server/controllers/util.js
> +    res.status(500).send();
yeah we can do both

2024-06-14 13:09 UTC, sebastiandve commented on server/controllers/index.js
hehe I didn't know until I tried

2024-06-14 18:00 UTC, tatyanabortnik approved these changes
Geht :)

2024-06-15 08:18 UTC, Wyna-7 approved these changes

2024-06-15 08:18 UTC, merged