Refactor/js to ts
Wyna-7/digestwell-repo pull request #22
Opened 2024-06-17 18:31 UTC by Wyna-7

2024-06-17 18:46 UTC, tatyanabortnik commented on client/src/App.tsx
> +import { Container, Box } from '../node_modules/@mui/material/index';
i still import this line and next as import { Box, Container } from '@mui/material';
why rewriting this?

2024-06-17 18:50 UTC, tatyanabortnik commented on client/src/App.tsx
> +  const [entriesList, setEntriesList] = useState<object[]>([]);
this object should be an Entry type/inteface i think. Like useState<Entry[]> | undefined ?
 can leave it like this for now and then import my types file

2024-06-17 18:50 UTC, tatyanabortnik commented on client/src/App.tsx
> +      setEntriesList(data.map((entry: { id: number; createdAt: string; name: string; select: string; health_impact: string; stool_type: string; is_bleeding: boolean; other_symptoms: string; userId: n
here we will also use Entry type

2024-06-17 18:51 UTC, tatyanabortnik commented on client/src/apiService.ts
dont commit this file, Sebastian updated it

2024-06-17 18:53 UTC, tatyanabortnik commented on client/src/components/EntriesForm/EntriesForm.tsx
> +  const [formData, setFormData] = useState<{ item: string; selectedOption: string; otherSymptoms: string; selectedStoolType: string; bloodInStool: boolean }>({
this should also be defined in a separate interface ?

2024-06-17 18:55 UTC, tatyanabortnik commented on client/src/components/EntriesForm/EntriesForm.tsx
> +    const newItem: { name: string; select: string; other_symptoms: string; stool_type: string; is_bleeding: boolean; userId: number } = {
here too)

2024-06-17 18:57 UTC, tatyanabortnik reviewed
Left some comments, but most of them we can fix after we merge our typescripts. Dont commit apiService

2024-06-18 07:31 UTC, Wyna-7 commented on client/src/App.tsx
> +import { Container, Box } from '../node_modules/@mui/material/index';
not sure why, but it errored out unless I gave it the specific path :/
we can test if it errors out in you machine, if it does it must be some config on my end that is different

2024-06-18 07:31 UTC, Wyna-7 commented on client/src/App.tsx
> +  const [entriesList, setEntriesList] = useState<object[]>([]);
it should! since we will need to import the type from Entry, I left it as object for now

2024-06-18 07:34 UTC, Wyna-7 commented on client/src/components/EntriesForm/EntriesForm.tsx
> +  const [formData, setFormData] = useState<{ item: string; selectedOption: string; otherSymptoms: string; selectedStoolType: string; bloodInStool: boolean }>({
yes, we should definetly extract these and have them in a types file

2024-06-18 07:35 UTC, Wyna-7 commented on client/src/context/EntriesContext.ts
> +const EntriesContext = createContext<any>(null);
I think once we get everything together, we can check what we have in the context, store everything in an interface object and pass that instead of any

2024-06-18 10:07 UTC, sebastiandve requested changes
just a small change

2024-06-18 11:11 UTC, closed without merging